name: Create Release with macOS ARM Build

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version'
        required: true

jobs:
  build-and-release:
    uses: d-pacheco/PCMS/.github/workflows/macos-build-arm.yml@main

  create-release:
    runs-on: ubuntu-latest
    needs: build-and-release

    steps:
      # Step 1: Download the artifact produced by Action 1
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: macOS-app-arm

      # Step 2: Create GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.event.inputs.release_version }}
          release_name: Release ${{ github.event.inputs.release_version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Upload the artifact to the release
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/PCMS_arm
          asset_name: PCMS_arm
          asset_content_type: application/octet-stream
