name: Create Release with macOS ARM Build

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version'
        required: true

jobs:
  release-job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Call Action 1 to build and upload the artifact
      - name: Call Build for macOS ARM
        uses: d-pacheco/PCMS/.github/workflows/build-macos-arm.yml@main

      # Step 2: Download the artifact produced by Action 1
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: macOS-app-arm  # Must match the artifact name from Action 1

      # Step 3: Create GitHub Release
      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.event.inputs.release_version }}  # Tag name provided as input
          release_name: Release ${{ github.event.inputs.release_version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token to create the release

      # Step 4: Upload the artifact to the release
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}  # Upload URL from the release step
          asset_path: dist/PCMS_arm  # Path to the artifact downloaded from Action 1
          asset_name: PCMS_arm  # Name of the asset in the release
          asset_content_type: application/octet-stream
