name: Build for macOS Intel

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-macos:
    runs-on: macos-13

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements-base.txt

      # Step 4: Build the project with PyInstaller
      - name: Build with PyInstaller
        run: |
          pip install pyinstaller
          arch -x86_64 pyinstaller -F main_gui.py -n 'PCMS_intel'

      # Step 5: Upload the built artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS-app-intel
          path: dist/
