name: Build for macOS

on:
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements-base.txt

      # Step 4: Build the project with PyInstaller
      - name: Build with PyInstaller
        run: |
          pip install pyinstaller
          pyinstaller -F main.py -n 'PCMS'

      # Step 5: Upload the built artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: macOS-app
          path: dist/
